### ISSUE TITLE
Database model

### ISSUE THREAD

**Issue by osycon** [chingu-voyage7/Bears-Team-19#6]
Set up a database model proposal

**Comment by chsanch** [comment]
I'm working on it, for now there are just a few tables, you can take a look at the documentation at:
`http://chsanch.info/db_docs/`
I'll be updating these documents when adding more tables.

**Comment by osycon** [comment]
Looks great! Am I missing somewhere on how to input incomes?
Perhaps if we want to add multiple bank accounts to the user we could add a column to the expense table called "account"?
How do we keep track of notifications/reminders on going over budget? Is this something we would handle in database or somewhere else?
Just my thoughts. :)

**Comment by chsanch** [comment]
We can handle notifications from PostgreSQL, we just need to know how will be the `trigger` amount to create the notification.  (See #9)

**Comment by osycon** [comment]
We are going to need CRUD for expenses, incomes and users
On users we would need following fields:
- email
- password
- name
- notifications (on or off) so a boolean on that I guess.
- createdAt
- updatedAt

Expenses and income fields are likely the same. Maybe we should have a transaction table instead and just add a field called Action? Like this.
- action: (expense or income, which means the amount would be either positive or negative).
- amount (should be stored in a low denominator such as cent)
- date for the expense
- category (Food, home loan etc)

Question: Should category be an enum list or should it be a free text field under transaction?

Are there any other things we need? I can't come up with more right now.

**Comment by osycon** [comment]
Thought of something.
Budget could either be its own table or it could be a property of the user depending on how advanced we would like it.
If it is on a user it could be a target amount for the month only. That when it goes over, it says "over budget" on users account or in some place when user is logged in.
If it is its own table, I'm not sure what fields besides amount.

Thoughts?

**Comment by chsanch** [comment]
Hi, I've modified the tables, all of them have now `created_at` and `updated_at`, every time one of the fields are modified the `updated_at` will be updated as well.

Now regarding the `password` field in `users` I don't think it is a good idea to stored it there, not sure if you have looked at the documentation of `PostgREST` but they recommend to use another schema to store user information, I think this should be managed from the Passport middleware and then from there we can access the REST API with the user id and the JWT Token.

About `currency` right now this is handled by Postgres, with the data type `money` which allow to handle the currency symbol based in the locale configuration of the server, maybe we can leave this as it and not to worry about it at this point. Also this could be maybe managed from a table user_preferences or something similar.

Incomes and Expenses are similar, but as we are using PostgREST, it will exposed any table as and Endpoint, so it's easier to have both  `/expenses` and `/incomes` endpoints and not to create an extra logic layer in the database.
